# Generated by Django 4.2.7 on 2023-11-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FactSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.JSONField()),
                ('templates', models.ManyToManyField(through='main.Carton', to='main.template')),
            ],
        ),
        migrations.AddField(
            model_name='carton',
            name='fact_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factset'),
        ),
        migrations.AddField(
            model_name='carton',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.template'),
        ),
    ]
