# Generated by Django 4.2.7 on 2023-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factset',
            name='name',
            field=models.CharField(default='<django.db.models.fields.AutoField>', max_length=50),
        ),
        migrations.AlterField(
            model_name='factset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
