# Generated by Django 4.2.7 on 2023-12-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_factset_name_alter_factset_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factset',
            name='name',
        ),
    ]
