# Generated by Django 4.2.7 on 2023-12-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_factset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='factset',
            name='nameKey',
            field=models.CharField(default='Target', max_length=50),
        ),
    ]
