# Generated by Django 4.2.7 on 2023-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_factset_namekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='Template', max_length=50),
        ),
    ]
