# Generated by Django 4.2.7 on 2023-12-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fields', models.JSONField()),
                ('templates', models.ManyToManyField(to='main.template')),
            ],
        ),
    ]
