# Generated by Django 4.2.7 on 2023-12-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fieldcollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldcollection',
            old_name='fields',
            new_name='allTemplateFields',
        ),
        migrations.RemoveField(
            model_name='fieldcollection',
            name='templates',
        ),
        migrations.AddField(
            model_name='template',
            name='field_collection',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='main.fieldcollection'),
            preserve_default=False,
        ),
    ]
