# Generated by Django 4.2.7 on 2023-12-04 15:11

from django.db import migrations, models
import django.db.models.deletion



def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FactSetSchema = apps.get_model("main", "FactSetSchema")
    db_alias = schema_editor.connection.alias
    FactSetSchema.objects.using(db_alias).create(
        fields=[],
        name="Sample",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fieldcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactSetSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(forwards_func,  reverse_code=migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='factset',
            name='nameKey',
        ),
        migrations.AddField(
            model_name='factset',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='factset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='FieldCollection',
        ),
        migrations.AddField(
            model_name='factset',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.factsetschema'),
            preserve_default=False,
        ),
    ]
