# Generated by Django 4.2.7 on 2023-12-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_fields_fieldcollection_alltemplatefields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
