# Generated by Django 5.0 on 2023-12-04 15:19

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_factsetschema_remove_factset_namekey_factset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factset',
            name='facts',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='factsetschema',
            name='fields',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
