# Generated by Django 5.0 on 2023-12-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_factset_facts_alter_factsetschema_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factsetschema',
            old_name='fields',
            new_name='schema',
        ),
    ]
