# Generated by Django 4.2.7 on 2023-12-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_template_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='field_collection',
        ),
    ]
