# Generated by Django 4.2.7 on 2023-12-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_template_field_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldcollection',
            name='allTemplateFields',
        ),
    ]
