# Generated by Django 5.0 on 2023-12-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_fields_factsetschema_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.factsetschema'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Carton',
            new_name='Card',
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='main.card')),
                ('subdecks', models.ManyToManyField(to='main.deck')),
            ],
        ),
    ]
