# Generated by Django 5.0 on 2023-12-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
